function [masked_stack,mask] = incidence_mask(stack,incloc,threshAngle)
%
%
%	Function to mask coherence stack by local incidence angle, such that 
%	only coherence images with a good satellite view are used. Must be done
%	separately for the ascending and descending tracks!
%
%	Local incidence angle is the angle between the satellite LOS and the
%	surface normal. Therefore lower incidence angle corresponds to better
%	view of the surface from the satellite and incorporates both satellite
%	look angle and hillslope surface angle.
%
%
%   INPUTS:
%       stack           stack of coherence images generated by create_coherence_stack.m
%                       (cell structure of GRIDobj)
%       incloc          local incidence angle (GRIDobj)
%       threshAngle     threshold local incidence angle range, above which pixels will
%                       be thrown out (two floats).
%
%   OUTPUTS:    
%       masked_stack    coherence stack with the incidence mask applied to
%                       all images in stack
%       mask            geotiff of mask applied
%
%   S. Olen, 06.11.2019



% Create incidence angle mask
% Resample incloc to the resolution of the coherence stack
incloc = resample(incloc,stack{1}.coh);

% Define mask by trehshold local incidence angle
mask = incloc > tangle(1) & incloc < tangle(2);

% 2:
%	Mask coherence stack.
masked_stack = stack;
for i = 1:length(stack)
	masked_stack{i}.coh.Z(~mask.Z) = NaN;
end
